Added control related ROS2 interfaces to ControlBoard_nws_ros2
robotology-playground/yarp-devices-ros2 pull request #36
Opened 2022-07-26 08:46 UTC by elandini84

This is a different take on the new feature added in [PR #35](https://github.com/robotology-playground/yarp-ros2/pull/35). Instead of adding a new device, the "control functionalities" have been added to `controlBoard_nws_ros2`.

This new feature can be enabled by passing the `msgs_name` parameter to the device itself.
As for the device in the aforementioned PR, this new version of `controlBoard_nws_ros2` has been tested in simulation with the model `cer_no_collisions_20m`.

To try it out please use this branch on `cer-sim` repo: [test/ros2/controlBoard_nws/new_parameter](https://github.com/elandini84/cer-sim/tree/test/ros2/controlBoard_nws/new_parameter)

2022-07-26 10:04 UTC, randaz81 requested changes

2022-07-26 10:04 UTC, randaz81 commented on src/devices/controlBoard_nws_ros2/ControlBoard_nws_ros2.cpp
> +    bool *done = new bool[1];
?

2022-07-26 15:07 UTC, elandini84 commented on src/devices/controlBoard_nws_ros2/ControlBoard_nws_ros2.h
> + * | msgs_name      |      -         | string  | -              |   -           | No                          | set the base name for the topics and interfaces                   | If it is not specif
Typo and error removed

2022-07-26 15:07 UTC, elandini84 commented on ros2_interfaces_ws/src/yarp_control_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
Changed accordingly to suggestion

2022-07-26 15:07 UTC, elandini84 commented on src/devices/controlBoard_nws_ros2/ControlBoard_nws_ros2.cpp
> +        }
Removed

2022-07-26 15:07 UTC, elandini84 commented on src/devices/controlBoard_nws_ros2/ControlBoard_nws_ros2.cpp
> +    bool *done = new bool[1];
Removed since not needed anymore

2022-07-26 15:08 UTC, elandini84 commented on src/devices/controlBoard_nws_ros2/ControlBoard_nws_ros2.cpp
> +const std::vector<std::string> implementedCtrlModes{"POSITION",
IDLE control mode added

2022-08-17 11:58 UTC, randaz81 approved these changes

2022-08-17 12:04 UTC, randaz81 approved these changes

2022-08-17 12:05 UTC, merged